apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: lagspill-bot
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 0
    max: 0
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 256Mi
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: lagspill-bot
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
  readiness:
    path: /api/internal/is_ready
    initialDelay: 10
  envFrom:
    - secret: lagspill-bot-secrets
